
import streamlit as st
import os
import json
import hashlib
import requests
import datetime
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import email
from email import policy
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

# --- Streamlit Page Configuration & Modern Theme Setup ---
st.set_page_config(
    page_title="EmailGuard Security & Forensic Suite", 
    page_icon="🛡️", 
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Custom CSS for Modern UI Design ---
st.markdown("""
    <style>
    .main {
        background-color: #0f172a;
        color: #f8fafc;
    }
    .stSidebar {
        background-color: #1e293b;
    }
    h1, h2, h3 {
        color: #38bdf8 !important;
        font-family: 'Segoe UI', sans-serif;
    }
    .stButton>button {
        background: linear-gradient(135deg, #0284c7 0%, #0369a1 100%);
        color: white;
        border-radius: 8px;
        padding: 0.6rem 1.2rem;
        font-weight: 600;
        border: none;
        box-shadow: 0 4px 6px rgba(0,0,0,0.2);
        transition: all 0.3s ease;
    }
    .stButton>button:hover {
        background: linear-gradient(135deg, #0369a1 0%, #075985 100%);
        box-shadow: 0 6px 8px rgba(0,0,0,0.3);
    }
    </style>
""", unsafe_allow_html=True)

# --- Email Alert Function ---
def send_login_alert(user_email, status):
    sender_email = "YOUR_REAL_EMAIL@gmail.com"  
    sender_password = "YOUR_16_DIGIT_APP_PASSWORD" 
    receiver_email = "YOUR_REAL_EMAIL@gmail.com" 
    
    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = receiver_email
        msg['Subject'] = f"🚨 EmailGuard Security Alert: Login Attempt ({status})"
        
        body = f"""
        Hello Admin,
        
        A login attempt was made on your EmailGuard Security Suite dashboard.
        
        - Attempted Email: {user_email}
        - Status: {status}
        - Timestamp: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
        
        If this was you, you can safely ignore this message. If not, please secure your system immediately!
        """
        msg.attach(MIMEText(body, 'plain'))
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
        server.quit()
    except Exception as e:
        print(f"Email alert failed: {e}")

# --- Initialize Session States ---
if "logged_in" not in st.session_state:
    st.session_state.logged_in = False

if "reset_key" not in st.session_state:
    st.session_state.reset_key = 0

if "nav_index" not in st.session_state:
    st.session_state.nav_index = 0

if "scanned_data" not in st.session_state:
    st.session_state.scanned_data = {
        "timestamp": "",
        "sender": "",
        "subject": "",
        "spf": "-- Select Option --",
        "dkim": "-- Select Option --",
        "dmarc": "-- Select Option --",
        "ip": "",
        "country": "",
        "isp": "",
        "risk_score": 0,
        "alerts_summary": ""
    }

DB_FILE = "alias_database.json"

def load_alias_data():
    if os.path.exists(DB_FILE):
        with open(DB_FILE, 'r') as f:
            return json.load(f)
    return {}

def save_alias_data(data):
    with open(DB_FILE, 'w') as f:
        json.dump(data, f, indent=4)

def get_ip_geolocation(ip_address):
    try:
        response = requests.get(f"http://ip-api.com/json/{ip_address}", timeout=5)
        data = response.json()
        if data.get("status") == "success":
            return data.get("country", "Unknown"), data.get("isp", "Unknown")
    except Exception:
        pass
    return "Unknown", "Unknown"

def generate_forensic_report(report_data, output_filename="Email_Forensic_Report.pdf"):
    doc = SimpleDocTemplate(output_filename, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], fontSize=18, textColor=colors.HexColor("#0284c7"), alignment=1, spaceAfter=15)
    heading_style = ParagraphStyle('HeadingStyle', parent=styles['Heading2'], fontSize=13, textColor=colors.HexColor("#0369a1"), spaceBefore=10, spaceAfter=6)
    normal_style = styles['Normal']
    
    story.append(Paragraph("EMAIL SECURITY & FORENSIC REPORT", title_style))
    story.append(Paragraph("<b>Generated by:</b> EmailGuard Advanced Security Suite", normal_style))
    story.append(Paragraph(f"<b>Timestamp:</b> {report_data.get('timestamp', 'N/A')}", normal_style))
    story.append(Spacer(1, 15))
    
    story.append(Paragraph("1. Email Header & Domain Authentication", heading_style))
    header_info = [
        ["Sender Email:", report_data.get('sender', 'Unknown')],
        ["Subject:", report_data.get('subject', 'Unknown')],
        ["SPF Status:", report_data.get('spf', 'N/A')],
        ["DKIM Status:", report_data.get('dkim', 'N/A')],
        ["DMARC Status:", report_data.get('dmarc', 'N/A')],
    ]
    t1 = Table(header_info, colWidths=[120, 380])
    t1.setStyle(TableStyle([('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f1f5f9")), ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")), ('PADDING', (0,0), (-1,-1), 6)]))
    story.append(t1)
    story.append(Spacer(1, 12))
    
    story.append(Paragraph("2. Threat Intelligence & IP Geolocation", heading_style))
    ip_info = [
        ["Sender IP Address:", report_data.get('ip', 'N/A')],
        ["Country Location:", report_data.get('country', 'N/A')],
        ["ISP / Organization:", report_data.get('isp', 'N/A')],
    ]
    t2 = Table(ip_info, colWidths=[120, 380])
    t2.setStyle(TableStyle([('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#fef3c7")), ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#fde68a")), ('PADDING', (0,0), (-1,-1), 6)]))
    story.append(t2)
    story.append(Spacer(1, 12))
    
    story.append(Paragraph("3. Content Inspection & Risk Assessment", heading_style))
    risk_score = report_data.get('risk_score', 0)
    status_text = "HIGH RISK / PHISHING" if risk_score >= 50 else "LOW RISK / CLEAN"
    risk_info = [
        ["Final Risk Score:", f"{risk_score} / 100"],
        ["System Status:", status_text],
        ["Detected Alerts:", report_data.get('alerts_summary', 'None')],
    ]
    t3 = Table(risk_info, colWidths=[120, 380])
    t3.setStyle(TableStyle([('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#fee2e2") if risk_score >= 50 else colors.HexColor("#dcfce7")), ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#fca5a5") if risk_score >= 50 else colors.HexColor("#86efac")), ('PADDING', (0,0), (-1,-1), 6)]))
    story.append(t3)
    
    doc.build(story)
    return output_filename

# --- LOGIN PAGE LOGIC ---
if not st.session_state.logged_in:
    st.title("🔐 EmailGuard Suite - Secure Login")
    st.markdown("Please enter your real email address and system password to access the forensic dashboard.")
    
    col1, col2 = st.columns(2)
    with col1:
        login_email = st.text_input("Real Email Address", placeholder="e.g., yourname@gmail.com")
        login_pass = st.text_input("System Password", type="password", placeholder="Enter secure password")
        
        if st.button("Login to Dashboard"):
            if login_email and login_pass:
                if login_pass == "admin123":
                    st.session_state.logged_in = True
                    send_login_alert(login_email, "SUCCESSFUL LOGIN")
                    st.success("Login successful! Loading dashboard and sending email alert...")
                    st.rerun()
                else:
                    send_login_alert(login_email, "FAILED LOGIN (Wrong Password)")
                    st.error("🚨 SECURITY ALERT: Invalid password! Access denied & alert email sent.")
            else:
                st.warning("⚠️ SECURITY ALERT: Both Email and Password are required to login!")
    st.stop()

# --- Pages List ---
pages = [
    "Dashboard Home", 
    "1. Header & Risk Analyzer", 
    "2. Content & Malware Inspector", 
    "3. Privacy Alias Tracker", 
    "4. PDF Forensic Report"
]

# --- Sidebar Modern Navigation & Reset Option ---
st.sidebar.markdown("## 🛡️ EmailGuard Suite")
selected_menu = st.sidebar.selectbox("Navigation Panel", pages, index=st.session_state.nav_index)

if selected_menu != pages[st.session_state.nav_index]:
    st.session_state.nav_index = pages.index(selected_menu)
    st.rerun()

st.sidebar.markdown("---")
if st.sidebar.button("🔄 Reset / Clear Data"):
    st.session_state.scanned_data = {
        "timestamp": "",
        "sender": "",
        "subject": "",
        "spf": "-- Select Option --",
        "dkim": "-- Select Option --",
        "dmarc": "-- Select Option --",
        "ip": "",
        "country": "",
        "isp": "",
        "risk_score": 0,
        "alerts_summary": ""
    }
    st.session_state.reset_key += 1
    st.rerun()

st.sidebar.markdown("---")
if st.sidebar.button("🔒 Logout"):
    st.session_state.logged_in = False
    st.rerun()

# --- Page Contents Based on State ---
menu = pages[st.session_state.nav_index]

if menu == "Dashboard Home":
    st.title("🛡️ Email Security & Forensic Suite")
    st.markdown("### Advanced Automated Phishing Detection & Forensic Analysis Dashboard")
    st.markdown("---")
    
    col1, col2, col3 = st.columns(3)
    with col1:
        st.markdown("### 🔍 Header Analyzer")
        st.write("Inspect SPF, DKIM, DMARC records and trace sender routing hops automatically.")
    with col2:
        st.markdown("### 🦠 Content Inspector")
        st.write("Scan phishing keywords, malicious URLs, and verify file attachments via VirusTotal hashes.")
    with col3:
        st.markdown("### 📄 Forensic Reports")
        st.write("Generate professional downloadable PDF investigation reports instantly.")

elif menu == "1. Header & Risk Analyzer":
    st.header("🔍 Email Header Parser & Risk Scoring")
    st.markdown("⚠️ **Note:** All fields below are **mandatory** and must be filled completely to run the analysis.")
    
    col1, col2 = st.columns(2)
    with col1:
        spf = st.selectbox("SPF Status *", ["-- Select Option --", "Pass", "Fail"], key=f"spf_{st.session_state.reset_key}")
        dkim = st.selectbox("DKIM Status *", ["-- Select Option --", "Pass", "Fail"], key=f"dkim_{st.session_state.reset_key}")
    with col2:
        dmarc = st.selectbox("DMARC Status *", ["-- Select Option --", "Pass", "Fail"], key=f"dmarc_{st.session_state.reset_key}")
        sender_ip = st.text_input("Sender IP Address *", value=st.session_state.scanned_data.get("ip", ""), placeholder="Enter IP address (e.g., 185.220.101.5)", key=f"ip_{st.session_state.reset_key}")
        sender_email = st.text_input("Sender Email Address *", value=st.session_state.scanned_data.get("sender", ""), placeholder="Enter sender email", key=f"email_{st.session_state.reset_key}")
        subject = st.text_input("Email Subject *", value=st.session_state.scanned_data.get("subject", ""), placeholder="Enter email subject", key=f"sub_{st.session_state.reset_key}")
        
    if st.button("Analyze Risk & Intelligence"):
        if spf == "-- Select Option --" or dkim == "-- Select Option --" or dmarc == "-- Select Option --" or not sender_ip or not sender_email or not subject:
            st.error("🚨 SECURITY ALERT: All mandatory fields must be filled and options must be selected before analysis!")
        else:
            risk = 0
            if spf == "Fail": risk += 30
            if dkim == "Fail": risk += 30
            if dmarc == "Fail": risk += 40
            
            country, isp = get_ip_geolocation(sender_ip)
            
            st.session_state.scanned_data = {
                "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "sender": sender_email,
                "subject": subject,
                "spf": spf,
                "dkim": dkim,
                "dmarc": dmarc,
                "ip": sender_ip,
                "country": country,
                "isp": isp,
                "risk_score": risk,
                "alerts_summary": f"SPF: {spf}, DKIM: {dkim}, DMARC: {dmarc}, IP Location: {country}, ISP: {isp}"
            }
            
            st.subheader("📊 Analysis Results")
            st.metric(label="Calculated Risk Score", value=f"{risk} / 100")
            
            if risk >= 70:
                st.error("🔴 SECURITY ALERT: HIGH RISK / SPOOFED DOMAIN DETECTED!")
            elif risk > 0:
                st.warning("🟡 SECURITY WARNING: MEDIUM RISK FOUND")
            else:
                st.success("🟢 STATUS: LOW RISK / AUTHENTIC EMAIL")
                
            st.markdown("### 🌍 Sender IP Threat Intelligence")
            col_a, col_b = st.columns(2)
            with col_a:
                st.info(f"**Country Location:** {country}")
            with col_b:
                st.info(f"**ISP / Organization:** {isp}")
                
            st.success("✅ Results saved successfully! You can now view them in the PDF Forensic Report module.")

elif menu == "2. Content & Malware Inspector":
    st.header("🦠 Content Inspection & Phishing Detector")
    st.markdown("⚠️ **Note:** Email body text is mandatory for phishing content scanning.")
    
    email_body = st.text_area("Enter Email Body Text for Phishing Scan *", placeholder="Paste the email body text here...", key=f"body_{st.session_state.reset_key}")
    
    if st.button("Inspect Content"):
        if not email_body.strip():
            st.error("🚨 SECURITY ALERT: Email body text cannot be empty!")
        else:
            score = 0
            alerts = []
            keywords = ["urgent", "verify your account", "password reset", "bank account suspended", "click here", "claim prize"]
            found = [kw for kw in keywords if kw in email_body.lower()]
            
            if found:
                score += 40
                alerts.append(f"Phishing Keywords Found: {found}")
                
            st.session_state.scanned_data["risk_score"] = score
            st.session_state.scanned_data["alerts_summary"] = f"Content keywords detected: {found}"
            
            st.subheader("🔍 Inspection Findings")
            if alerts:
                for alert in alerts:
                    st.warning(f"🚨 {alert}")
            else:
                st.success("No phishing keywords detected in content.")
            st.metric("Content Risk Score", f"{score} / 100")

elif menu == "3. Privacy Alias Tracker":
    st.header("🕵️ Email Masking & Leak Tracker")
    st.markdown("⚠️ **Note:** Both Service Name and Real Email are mandatory.")
    
    service = st.text_input("Service Name *", placeholder="e.g., Daraz, Netflix", key=f"serv_{st.session_state.reset_key}")
    real_email = st.text_input("Your Real Email Address *", placeholder="e.g., yourname@gmail.com", key=f"real_{st.session_state.reset_key}")
    
    if st.button("Generate Masked Alias"):
        if not service or not real_email:
            st.error("🚨 SECURITY ALERT: All alias fields must be filled!")
        else:
            username = service.lower().replace(" ", "_")
            masked = f"{username}_safe_mask@emailguard.local"
            data = load_alias_data()
            data[masked] = {"service": service, "real_email": real_email, "status": "Active", "hit_count": 0, "created_at": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
            save_alias_data(data)
            st.success(f"✅ Masked Email Generated: **{masked}**")
            
    st.markdown("---")
    st.subheader("📁 Stored Aliases Database")
    data = load_alias_data()
    if data:
        st.json(data)
    else:
        st.info("No aliases created yet.")

elif menu == "4. PDF Forensic Report":
    st.header("📄 Automated PDF Forensic Report Generator")
    st.markdown("⚠️ **Note:** Verify all fields before generating the final forensic report.")
    
    current_data = st.session_state.scanned_data
    
    sender = st.text_input("Sender Email *", value=current_data.get("sender", ""), placeholder="Enter sender email", key=f"pdf_sender_{st.session_state.reset_key}")
    subject = st.text_input("Email Subject *", value=current_data.get("subject", ""), placeholder="Enter email subject", key=f"pdf_sub_{st.session_state.reset_key}")
    ip_addr = st.text_input("Sender IP *", value=current_data.get("ip", ""), placeholder="Enter sender IP", key=f"pdf_ip_{st.session_state.reset_key}")
    score = st.slider("Risk Score", 0, 100, int(current_data.get("risk_score", 0)), key=f"pdf_score_{st.session_state.reset_key}")
    
    if st.button("Generate Forensic PDF Report"):
        if not sender or not subject or not ip_addr:
            st.error("🚨 SECURITY ALERT: All report fields are mandatory and cannot be empty!")
        else:
            country, isp = get_ip_geolocation(ip_addr)
            report_data = {
                "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "sender": sender,
                "subject": subject,
                "spf": current_data.get("spf", "Pass"),
                "dkim": current_data.get("dkim", "Pass"),
                "dmarc": current_data.get("dmarc", "Pass"),
                "ip": ip_addr,
                "country": country,
                "isp": isp,
                "risk_score": score,
                "alerts_summary": current_data.get("alerts_summary", "Manual review triggered.")
            }
            
            pdf_file = generate_forensic_report(report_data)
            st.success(f"✅ PDF Report generated successfully as '{pdf_file}'!")
            
            with open(pdf_file, "rb") as f:
                st.download_button("📥 Download Forensic PDF Report", f, file_name=pdf_file, mime="application/pdf")

# --- Validation Logic for Next Page Button ---
st.markdown("---")
col_prev, col_next = st.columns([1, 1])

with col_prev:
    if st.session_state.nav_index > 0:
        if st.button("⬅️ Previous Page"):
            st.session_state.nav_index -= 1
            st.rerun()

with col_next:
    if st.session_state.nav_index < len(pages) - 1:
        if st.button("Next Page ➡️"):
            can_proceed = True
            error_message = ""
            
            # Check requirements based on current page
            current_page_name = pages[st.session_state.nav_index]
            
            if current_page_name == "1. Header & Risk Analyzer":
                data = st.session_state.scanned_data
                if not data.get("sender") or not data.get("subject") or not data.get("ip") or data.get("spf") == "-- Select Option --":
                    can_proceed = False
                    error_message = "⚠️ Please complete the Header & Risk Analysis and click 'Analyze Risk & Intelligence' before proceeding!"
            
            elif current_page_name == "2. Content & Malware Inspector":
                if st.session_state.scanned_data.get("risk_score", 0) == 0 and not st.session_state.scanned_data.get("alerts_summary"):
                    # Optional: You can enforce content scanning completion if needed
                    pass
            
            if can_proceed:
                st.session_state.nav_index += 1
                st.rerun()
            else:
                st.error(error_message)