
import os
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def generate_forensic_report(report_data, output_filename="Email_Forensic_Report.pdf"):
    # Create PDF document setup
    doc = SimpleDocTemplate(output_filename, pagesize=letter,
                            rightMargin=40, leftMargin=40,
                            topMargin=40, bottomMargin=40)
    story = []
    
    # Styles definition
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=20,
        textColor=colors.HexColor("#1A237E"),
        alignment=1, # Center
        spaceAfter=15
    )
    
    heading_style = ParagraphStyle(
        'HeadingStyle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor("#0D47A1"),
        spaceBefore=10,
        spaceAfter=6
    )
    
    normal_style = styles['Normal']
    
    # Document Title
    story.append(Paragraph("EMAIL SECURITY & FORENSIC REPORT", title_style))
    story.append(Paragraph("<b>Generated by:</b> EmailGuard Security Suite", normal_style))
    story.append(Paragraph(f"<b>Timestamp:</b> {report_data.get('timestamp', 'N/A')}", normal_style))
    story.append(Spacer(1, 15))
    
    # 1. Header Analysis Section
    story.append(Paragraph("1. Email Header & Domain Authentication", heading_style))
    header_info = [
        ["Sender Email:", report_data.get('sender', 'Unknown')],
        ["Subject:", report_data.get('subject', 'Unknown')],
        ["SPF Status:", report_data.get('spf', 'N/A')],
        ["DKIM Status:", report_data.get('dkim', 'N/A')],
        ["DMARC Status:", report_data.get('dmarc', 'N/A')],
    ]
    t1 = Table(header_info, colWidths=[120, 380])
    t1.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#E8EAF6")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#C5CAE9")),
        ('PADDING', (0,0), (-1,-1), 6),
        ('TEXTCOLOR', (0,0), (0,-1), colors.HexColor("#333333")),
    ]))
    story.append(t1)
    story.append(Spacer(1, 12))
    
    # 2. Threat Intelligence & IP Geolocation
    story.append(Paragraph("2. Threat Intelligence & IP Geolocation", heading_style))
    ip_info = [
        ["Sender IP Address:", report_data.get('ip', 'N/A')],
        ["Country Location:", report_data.get('country', 'N/A')],
        ["ISP / Organization:", report_data.get('isp', 'N/A')],
    ]
    t2 = Table(ip_info, colWidths=[120, 380])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FFF3E0")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#FFE0B2")),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t2)
    story.append(Spacer(1, 12))
    
    # 3. Content Inspection & Risk Assessment
    story.append(Paragraph("3. Content Inspection & Risk Score", heading_style))
    risk_score = report_data.get('risk_score', 0)
    status_text = "HIGH RISK / PHISHING" if risk_score >= 50 else "LOW RISK / CLEAN"
    
    risk_info = [
        ["Final Risk Score:", f"{risk_score} / 100"],
        ["System Status:", status_text],
        ["Detected Alerts:", report_data.get('alerts_summary', 'None')],
    ]
    t3 = Table(risk_info, colWidths=[120, 380])
    t3.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FFEBEE") if risk_score >= 50 else colors.HexColor("#E8F5E9")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#FFCDD2") if risk_score >= 50 else colors.HexColor("#C8E6C9")),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t3)
    
    # Build PDF
    doc.build(story)
    print(f"\n✅ Success: Forensic PDF Report generated successfully as '{output_filename}'!")

def main():
    print("--- EMAIL FORENSIC PDF REPORT GENERATOR ---")
    print("Please enter the email scan details below to generate the PDF report:\n")
    
    report_data = {
        "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "sender": input("Enter Sender Email (e.g., sender@domain.com): "),
        "subject": input("Enter Email Subject: "),
        "spf": input("Enter SPF Status (Pass/Fail): "),
        "dkim": input("Enter DKIM Status (Pass/Fail): "),
        "dmarc": input("Enter DMARC Status (Pass/Fail): "),
        "ip": input("Enter Sender IP Address (e.g., 8.8.8.8): "),
        "country": input("Enter Country Location (e.g., USA): "),
        "isp": input("Enter ISP / Organization Name: "),
        "risk_score": int(input("Enter Final Risk Score (0-100): ") or 0),
        "alerts_summary": input("Enter Summary of Alerts/Findings: ")
    }
    
    output_pdf_name = input("Enter output PDF filename (default 'Email_Forensic_Report.pdf'): ").strip()
    if not output_pdf_name:
        output_pdf_name = "Email_Forensic_Report.pdf"
    if not output_pdf_name.endswith(".pdf"):
        output_pdf_name += ".pdf"
        
    generate_forensic_report(report_data, output_pdf_name)

if __name__ == "__main__":
    main()